# config/meta.yml

meta_product_name: "Müdi"
meta_title: "Müdi - Find activities based on how you want to feel."
meta_description: "With Müdi, simply put in your desired mood and let us find the perfect activity for you!"
meta_image: "cover.png" 
